In [23]:
import pandas as pd
import numpy as np
import joblib

In [5]:
test_data = pd.read_csv("data/processed/test_data.csv")

In [ ]:
raw = pd.read_csv("data/raw/Telco-Customer-Churn.csv")

In [73]:
raw.PaymentMethod.unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [6]:
test_data

,SeniorCitizen,tenure,InternetService,Contract,PaperlessBilling,MonthlyCharges,family_score,Internet_service_score,Payment_Electronic_check,Churn
0,0,31,0,2,0,20.90,0,-1.0,0,0
1,0,4,1,0,0,44.80,2,0.0,1,0
2,1,1,2,0,1,74.45,1,0.0,1,1
3,0,58,2,0,1,93.40,2,2.0,0,1
4,0,57,1,1,0,74.60,1,3.0,0,0
...,...,...,...,...,...,...,...,...,...,...
1404,0,12,0,2,0,19.35,1,-1.0,0,0
1405,0,65,2,2,1,104.10,2,2.0,0,0
1406,0,27,0,2,0,19.70,1,-1.0,0,0
1407,0,59,2,2,0,95.80,0,1.0,1,0
1408,0,1,2,0,1,102.45,2,2.0,1,1

In [ ]:
X = test_data.drop("Churn", axis=1).iloc[:5]
y = test_data.Churn.iloc[:5]

In [ ]:
dik = {
    "SeniorCitizen": 0,  # (0,1)
    "tenure": 3,  # in months
    "InternetService": 2,  # DSL = 1, Fiber Optic = 2, No = 0
    "Contract": 0,  # (0,2) month to month = 0, 1 year = 1, 2 year = 2
    "PaperlessBilling": 1,  # (0,1)
    "MonthlyCharges": 99,  # float
    "family_score": 0,  # Married (0,1) + Dependents (0,1)
    "Internet_service_score": -1,  # (-1, 4) TechSupport + DeviceProtection + OnlineBackup + OnlineSecurity, -1 if no internet service
    "Payment_Electronic_check": 1,  # (0,1)
}

In [68]:
dikk = pd.DataFrame(dik, index=[0])

In [69]:
dikk

,SeniorCitizen,tenure,InternetService,Contract,PaperlessBilling,MonthlyCharges,family_score,Internet_service_score,Payment_Electronic_check
0,0,3,2,0,1,99,0,-1,1

In [ ]:
model = joblib.load("models/best_model.joblib")

In [75]:
model.predict(dikk)

array([1])

In [74]:
model.predict_proba(dikk)

array([[0.25765769, 0.74234231]])